### ISSUE TITLE
Add tests in template

### ISSUE THREAD

**Issue by oncleben31** [oncleben31/cookiecutter-homeassistant-custom-component#10]
check how it's done in https://github.com/boralyl/cookiecutter-homeassistant-component

**Comment by oncleben31** [comment]
the PR https://github.com/custom-components/integration_blueprint/pull/50 could be a good source of inspiration.
Unless @raman325 is interested in doing a PR here.

**Comment by raman325** [comment]
I can take a look at this next week. I have never tried building a cookiecutter template before so this may end up going over my head, but can't hurt to try!

**Comment by oncleben31** [comment]
Thanks for considering contributing to this cookiecutter template.
You have two main ways to do it:
 - work directly in the cookiecutter and test by generating a project. It's mainly using jinja for all names that could be configurable by users (see [this file](https://github.com/oncleben31/cookiecutter-homeassistant-custom-component/blob/main/cookiecutter.json))
 - generate a project, work in the generated project and use [retrocookie](https://github.com/cjolowicz/retrocookie) to transfer your modifications in the template.

**Comment by raman325** [comment]
retrocookie is pretty cool, thanks for the reference! I will likely pursue that option when I get to this
